site_name: authz-analyzer
site_url: https://satoricyber.github.io/authz-analyzer
repo_url: https://github.com/satoricyber/authz-analyzer
repo_name: satoricyber/authz-analyzer
#strict: true

theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  homepage: https://satoricyber.github.io/authz-analyzer
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SatoriCyber
      name: Tweet
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SatoriCyber
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/satoricyber/authz-analyzer
      name: Github
    - icon: material/email
      link: "mailto:contact@satoricyber.com"
  google_analytics:
    - UA-154128939
    - auto

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Data Stores:
    - Amazon Redshift: datastores/redshift.md
    - Amazon S3: datastores/s3.md
    - Google BigQuery: datastores/bigquery.md
    - MongoDB: datastores/mongodb.md
    - PostgreSQL: datastores/postgresql.md
    - Snowflake: datastores/snowflake.md
  - Contributing: contributing.md
  - Changelog: changelog.md
